# fly.toml app configuration file generated for chest-cancer-detection-holy-glitter-4847 on 2025-04-28T08:52:49+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chest-cancer-detection-holy-glitter-4847'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
