# fly.toml app configuration file
app = 'chest-cancer-detection'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8080'

[[mounts]]
  source = 'chest_detection_data'
  destination = '/app/models'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'  # Use smaller instance type for API